-- Removing rows with negative sales amount
DELETE FROM pharmasales
WHERE sales<0;


-- Total revenue generated by each sales team in 2020
SELECT [sales team], SUM(sales) as total_revenue
FROM PharmaSales
WHERE year=2020
GROUP BY [sales team]
ORDER BY total_revenue DESC;


-- The product class that contributes the most to the total sales revenue
SELECT TOP 1 [product class], ROUND(SUM(sales),0) as total_revenue 
FROM PharmaSales
GROUP BY [Product Class]
ORDER BY total_revenue DESC;


-- Distribution of sales across different sub-channels in each channel
SELECT channel, [sub-channel], ROUND(SUM(sales),0) as total_sales
FROM pharmasales
GROUP BY channel, [sub-channel]
ORDER BY channel, total_sales DESC;

-- Who are the top-performing sales reps, and what are their total sales? 
SELECT TOP 10[Name of Sales Rep], ROUND(SUM(sales),0) AS total_sales
FROM pharmasales
GROUP BY [Name of Sales Rep]
ORDER BY total_sales DESC ;



-- Sales team with the highest average sales per product
WITH avgsales AS(
     SELECT [Sales Team] AS sales_team, [Product Name] AS product, ROUND(SUM(sales),0) AS sumsales
     FROM PharmaSales
     GROUP BY [Sales Team], [Product Name]
     )
SELECT TOP 1 sales_team, AVG(sumsales) AS avg_sales_per_product
FROM avgsales
GROUP BY sales_team
ORDER BY avg_sales_per_product DESC;


-- Year-over-year growth in sales for Germany
WITH SalesByYear AS(
     SELECT Country, Year, ROUND(SUM(sales),0) AS TotalSales
	 FROM PharmaSales
	 WHERE country ='Germany'
	 GROUP BY country, year 
),
SalesGrowth AS(
	 SELECT Country, Year, TotalSales, LAG(TotalSales)OVER(ORDER BY Year) AS PreviousYearSales
	 FROM SalesByYear
)
SELECT Country, Year, TotalSales, PreviousYearSales, 
       CASE 
	       WHEN PreviousYearSales IS NULL THEN NULL
		   ELSE (TotalSales - PreviousYearSales)*100/(PreviousYearSales)
	   END AS YearOverYearGrowth
FROM SalesGrowth;



-- List the months with the lowest sales for each year
WITH MonthlySales AS(
     SELECT Year, Month, SUM(sales) AS totalsales
     FROM PharmaSales
     GROUP BY Year, Month
),
LowestSales AS (
     SELECT Year, MIN(totalsales) AS LowestMonthlySale
	 FROM MonthlySales
	 GROUP BY year
)
SELECT a.Year, Month AS LowestSaleMonth , totalsales AS SalesAmount
FROM MonthlySales a JOIN LowestSales b
ON a.Year = b.year
WHERE a.totalsales=b.LowestMonthlySale
ORDER BY a.year



-- Retrieve the top 5 cities with the highest sales
SELECT TOP 5 city, SUM(sales) AS total_sales
FROM pharmasales
GROUP BY city
ORDER BY SUM(sales) DESC;


--What are the top 10 products by sales revenue across all distributors?  
SELECT TOP 10 [Product Name] AS product, ROUND(SUM(sales),0) AS total_sales
FROM pharmasales
GROUP BY [Product Name]
ORDER BY total_sales DESC


--What are the total sales across different channels (Hospital vs. Pharmacy) over time?
SELECT Channel, Year, ROUND(SUM(sales),0) AS total_sales
FROM pharmasales
GROUP BY channel,Year
ORDER BY channel, Year 


-- How do sales vary between different sub-channels (Govt, Institution, Private, Retail)?
SELECT [sub-Channel], ROUND(SUM(sales),0) AS total_sales
FROM pharmasales
GROUP BY [sub-Channel]
ORDER BY total_sales DESC
   -- Implies most revenue generated from retail pharmacies


-- Which distributors contribute the most to the sales? 
SELECT TOP 1 distributor, ROUND(SUM(sales),0) AS total_sales
FROM pharmasales
GROUP BY distributor
ORDER BY total_sales DESC

--Find the top 5 customers contributing to max. sales for each year
WITH Rankedsales AS(
     SELECT [Customer name], Year, ROUND(SUM(sales),0) AS total_sales, RANK()OVER(PARTITION BY Year ORDER BY ROUND(SUM(sales),0) DESC) AS Rank
     FROM pharmasales
     GROUP BY [Customer name], Year
)
SELECT * 
FROM Rankedsales
WHERE Rank<=5;


-- What product class are most commonly purchased by specific channels, sub-channels?
WITH mostcommon AS(
	 SELECT Channel, [Sub-Channel], [product class], COUNT([product class]) AS count
	 FROM pharmasales
	 GROUP BY Channel, [Sub-channel], [product class]
/
SELECT Channel, [Sub-Channel], [product class]
FROM mostcommon
WHERE count IN (SELECT MAX(count)
			   FROM mostcommon
			   GROUP BY Channel, [Sub-channel])


-- What is the average order size (quantity or sales) for different customer groups?
SELECT Channel, [Sub-Channel], AVG(Quantity) AS avg_quantity
FROM pharmasales
GROUP BY Channel, [Sub-channel]
ORDER BY AVG(Quantity) DESC,Channel, [Sub-channel]


-- which distributor contributed the most to sales each year?
WITH annualsales AS(
     SELECT year, ROUND(SUM(sales),0) as annual_sale
     FROM pharmasales
     GROUP BY year
),
distributorsales AS(
     SELECT distributor, year, ROUND(SUM(sales),0) AS d_annual_sale
     FROM pharmasales 
     GROUP BY distributor, year
)
SELECT a.year, b.distributor, (d_annual_sale*100/annual_sale) AS percent_contri
FROM annualsales a JOIN distributorsales b
ON a.year = b.year
WHERE (d_annual_sale*100/annual_sale) In (SELECT MAX(d_annual_sale*100/annual_sale) 
	                                      FROM annualsales a JOIN distributorsales b
	                                      ON a.year = b.year
										  GROUP BY a.year)
ORDER BY a.year


